<?php
return [
    'mode'                       => '',
    'format'                     => 'A4',
    'default_font_size'          => '12',
    'default_font'               => 'sans-serif',
    'margin_left'                => 10,
    'margin_right'               => 10,
    'margin_top'                 => 10,
    'margin_bottom'              => 10,
    'margin_header'              => 0,
    'margin_footer'              => 0,
    'orientation'                => 'P',
    'title'                      => 'Laravel mPDF',
    'author'                     => '',
    'creator'                    => '',
    'subject'                    => '',
    'keywords'                   => '',
    'watermark'                  => '',
    'show_watermark'             => false,
    'show_watermark_image'       => false,
    'watermark_font'             => 'sans-serif',
    'display_mode'               => 'fullpage',
    'watermark_text_alpha'       => 0.1,
    'watermark_image_path'       => '',
    'watermark_image_alpha'      => 0.2,
    'watermark_image_size'       => 'D',
    'watermark_image_position'   => 'P',
    'custom_font_dir'            => base_path("public/fonts"),
    'custom_font_data'           => [
        'ae_AlMohanad' => [
            'R'  => 'ae_AlMohanad.ttf',  
            'B'  => 'AL-Mohanad-Extra-Bold.ttf',     
            'I'  => 'ae_AlMohanad.ttf',     
            'BI' => 'AL-Mohanad-Extra-Bold.ttf',  
        ],
    ],
    'auto_language_detection'    => true,
    'temp_dir'                   => storage_path('app'),

];